services:

  test-backend:
    container_name: test-backend
    image: nginx:alpine
    network_mode: "host"
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        printf "events { worker_connections 10240; }
        http {
            keepalive_requests 1000000;
            keepalive_timeout 650;
            server {
                listen 11111;
                access_log off;
                location / {
                    return 200 'OK';
                }
            }
        }" > /etc/nginx/nginx.conf && nginx -g 'daemon off;'