site_name: ethlo r7 Gateway
site_description: The performant Java Gateway
site_url: https://r7.ethlo.com
repo_url: https://github.com/ethlo/r7
repo_name: ethlo/r7

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: amber
  features:
    - navigation.tabs
    - content.code.copy
    - toc.integrate
  logo: assets/r7.svg
  favicon: assets/r7.svg

nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Routes Configuration: routes_config.md
  - Server Configuration: server_config.md
  - Predicates: predicates.md
  - Filters: filters.md
  - Benchmarks: benchmarks.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format