version: ${git.rev.abbr}
routes:
  - id: forward-status
    upstream:
      targets:
        - url: http://localhost:18888
    match:
      - PathStartsWith:
          prefix: /my-secret-status
  - id: reject-benchmark
    upstream:
      targets:
        - url: http://localhost:1111
    match:
      - PathStartsWith:
          prefix: /benchmark
    filters:
      - SimpleMetrics
      - RequireAuthorizationHeader

  - id: undertow-internal-backend
    upstream:
      targets:
        - url: http://localhost:1111
    match:
      - PathStartsWith:
          prefix: /hello
      - Method:
          include:
            - GET
            - POST
    journal:
      request:
        level: NONE
        #status_overrides:
        #  2xx: METADATA
      response:
        level: NONE
    filters:
      - SimpleMetrics
      - RateLimiter:
          capacity: 10
          refill_tokens: 5
          refill_period: PT2s
      - AddResponseHeader:
          name: X-Gateway
          value: Venturi
      - CorrelationIdHeader
      - RequireAuthorizationHeader

  - id: ws-test
    upstream:
     targets:
       - url: http://127.0.0.1:8080
    match:
       PathStartsWith:
         prefix: /ws
    journal:
      request:
        level: METADATA
        status_overrides:
          5xx: HEADERS
      response:
        level: HEADERS
        status_overrides:
          2xx: NONE
    filters:
      - SimpleMetrics

  - id: home-assistant
    upstream:
      targets:
        - url: http://192.168.50.103:8123
    match:
      - PathStartsWith:
          prefix: /ha
    journal:
      request:
        level: METADATA
        status_overrides:
          5xx: HEADERS
      response:
        level: HEADERS
    filters:
      - SimpleMetrics
      - StripPathPrefix:
          parts: 1
