routes:
  - id: performance test to nginx
    uri:
      - http://localhost:1111
    match:
      and:
        - pathStartsWith: /hello
        - method:
          - GET
          - POST
    audit:
      request: FULL
      response: FULL
    filters:
      - type: AddResponseHeader
        args:
          name: X-Gateway
          value: Venturi