routes:
  - id: undertow-internal-backend
    upstream:
      targets:
        - url: http://localhost:1111
    match:
      - PathStartsWith:
          prefix: /hello
      - Method:
          include:
            - GET
            - POST
    journal:
      request:
        level: HEADERS
        status_overrides:
          2xx: METADATA
    filters:
      - AddResponseHeader:
          name: X-Gateway
          value: Venturi
      - CorrelationIdHeader
      - RequireAuthorizationHeader
  - id: external-test
    upstream:
      targets:
        - url: https://www.nrk.no
    match:
      - PathStartsWith:
          prefix: /nrk
    journal:
      request:
        level: METADATA
        status_overrides:
          5xx: HEADERS
      response:
        level: HEADERS
    filters:
      - StripPathPrefix:
          parts: 1