version: my-version-4.1
global_filters:
  - SimpleMetrics
  - AddCorrelationId
routes:
  - id: forward-status
    upstream:
      targets:
        - url: http://localhost:18888
    match:
      - PathPrefix:
          prefix: ${SECRET_URL:/status}
  - id: reject-benchmark
    upstream:
      targets:
        - url: http://localhost:1111
    match:
      - PathPrefix:
          prefix: /benchmark
    filters:
      - RequireAuthorizationHeader

  - id: undertow-internal-backend
    match:
      - PathPrefix:
          prefix: /hello
      - Method:
          include:
            - GET
            - POST
    upstream:
      targets:
        - url: http://localhost:1111
    filters:
      - RateLimiter:
          capacity: 5
          refill_tokens: 1
          refill_period: 2s
      - CircuitBreaker:
          failure_threshold: 10
          cooldown_period: 12s
      - AddResponseHeader:
          name: X-Powered-By
          value: Ethlo R7
      - AddCorrelationId
      - RequireAuthorizationHeader
    journal:
      request:
        level: NONE
        status_overrides:
          401,403: HEADERS
          429: METADATA
          5xx: HEADERS
      response:
        level: NONE

  - id: ws-test
    upstream:
      targets:
        - url: http://127.0.0.1:8080
    match:
      - PathPrefix:
          prefix: /ws
    journal:
      request:
        level: METADATA
        status_overrides:
          5xx: HEADERS
      response:
        level: HEADERS
        status_overrides:
          2xx: NONE

  - id: home-assistant
    upstream:
      targets:
        - url: http://192.168.50.103:8123
    match:
      - PathPrefix:
          prefix: /ha
    journal:
      request:
        level: METADATA
        status_overrides:
          5xx: HEADERS
      response:
        level: HEADERS
    filters:
      - StripPathPrefix:
          parts: 1
