services:
  r7-api:
    image: ethlo-r7:latest
    container_name: ethlo-r7-gateway
    ports:
      - "9999:8888"
      - "19999:18888"
    # ADD THIS TO UNBLOCK clone3:
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./config:/app/config:ro
      - ./journals:/journals:rw
    environment:
      - JAVA_TOOL_OPTIONS=
        -XX:+UseZGC
        --enable-native-access=ALL-UNNAMED
        --sun-misc-unsafe-memory-access=allow
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: 16
        reservations:
          memory: 200M

    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

    restart: unless-stopped