version: v2026-03-14

# Global filters applied to all routes
global_filters:
  - SimpleMetrics:
      period: 5M
      interval: 2S
  - RequestSizeLimit:
      max_size: 10MB

routes:

  - id: flaky-service
    match:
      - PathPrefix:
          prefix: /down
    upstream:
      targets:
        - url: http://localhost:22222
      health_check:
        path: /health
      fallback:
        route_id: denied

  - id: down
    filters:
    - ReturnResponse:
        status: 503
        content_type: text/plain
        body: We'll be back soon!

  - id: dashboard
    match:
      - PathPrefix:
          prefix: ${SECRET_URL:/status}
    upstream:
      targets:
        - url: http://localhost:18888

  - id: reject-benchmark
    match:
      - PathPrefix:
          prefix: /benchmark
    upstream:
      targets:
        - url: http://localhost:1111
    filters:
      - RequireAuthorizationHeader

  - id: static-content
    match:
      - not:
          PathPrefix:
            prefix: /hello
      - or:
          - Method:
              include:
                - GET
                - POST
          - RemoteAddr:
              source: 192.168.1.0/24
    upstream:
      targets:
        - url: http://localhost:1111
    filters:
      - RequireAuthorizationHeader
      - RateLimiter:
          capacity: 200000
          refill_tokens: 100000
          refill_period: 1s
      - CircuitBreaker:
          failure_threshold: 10
          cooldown_period: 15s
      - AddCorrelationId
    journal:
      request:
        level: HEADERS
        status_overrides:
          401,403: HEADERS
          429: METADATA
          5xx: HEADERS
      response:
        level: FULL

  - id: static-content-without-journal
    match:
      - PathPrefix:
          prefix: /hello
    upstream:
      targets:
        - url: http://localhost:1111
    filters:
      - RateLimiter:
          capacity: 50000
          refill_tokens: 12000
          refill_period: 1s
      - CircuitBreaker:
          failure_threshold: 10
          cooldown_period: 15s
      - RequireAuthorizationHeader
      - AddCorrelationId

  - id: ws-chat
    match:
      - PathPrefix:
          prefix: /ws
    upstream:
      targets:
        - url: http://127.0.0.1:8080
    journal:
      request:
        level: METADATA
        status_overrides:
          5xx: HEADERS
      response:
        level: HEADERS
        status_overrides:
          2xx: NONE

  - id: home-assistant
    match:
      - PathPrefix:
          prefix: /ha
    upstream:
      targets:
        - url: http://192.168.50.103:8123
    filters:
      - StripPathPrefix:
          parts: 1
    journal:
      request:
        level: METADATA
        status_overrides:
          5xx: HEADERS
      response:
        level: HEADERS