server:
  host: 0.0.0.0
  port: 8888

management:
  host: 0.0.0.0
  port: 18888

http:
  enable_http2: true
  always_set_keep_alive: true
  request_parse_timeout: 2s

proxy:
  connections_per_thread: 2000
  max_queue_size: 1000
  max_request_time: 60s
  ttl: 30s

limits:
  max_header_size: 8KB
  max_header_count: 50
  max_entity_size: 2MB
  max_parameter_count: 1000
  max_cookie_count: 200

storage:
  work_dir: /tmp/r7/journal
  shard_size: 200MB
  shard_count: 4
  pre_fault: false