name: Prune Old GHCR Images

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v3.0.1 
        with:
          image-names: r7-gateway
          cut-off: 3 days
          keep-n-most-recent: 2
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
